### ISSUE TITLE
1.20.1 crash on load world

### ISSUE THREAD

**Issue by SylisMC** [ChloePrime/Third-Person-Shooting-Zero#10]
Game crashed as soon as you load a world

Forge 47.3.0

Shoulder Surfing Reloaded [1.20.1-4.5.0] 
Third Person Shooting: Zero [1.20.1-5.0.1] 
Timeless & Classics Guns: Zero [1.0.3 ]

https://mclo.gs/XqNQKvh

**Comment by ChloePrime** [comment]
Use version 5.1.0

**Comment by SylisMC** [comment]
Aaah Fast reply. I got your mod from modrinth and the most recent version is 5.0.1. didnt think to check curseforge. thanks

**Comment by SylisMC** [comment]
Works mint. Thanks again.
