### ISSUE TITLE
1.18.2的ShoulderSurfing又㕛叒更新了

### ISSUE THREAD

**Issue by 8MiYile** [ChloePrime/Third-Person-Shooting-Zero#4]

**Comment by ChloePrime** [comment]
对1.18.2的支持已结束＞﹏＜
1.20.1版本正在适配中ヾ(≧▽≦*)o

**Comment by ChloePrime** [comment]
https://www.curseforge.com/minecraft/mc-mods/third-person-shooting/files/5417824
1.20.1的，发了

**Comment by 8MiYile** [comment]
1.18.2的支持已经结束了啊 好吧 那我尽量不更新ShoulderSurfing

**Comment by ChloePrime** [comment]
如果条件合适的话可以升级1.20.1哦

**Comment by 8MiYile** [comment]
哈哈 可惜了 我要是没开模组服就好了。。。
