### ISSUE TITLE
Crash on 1.19.2 version.

### ISSUE THREAD

**Issue by Ritotir** [ChloePrime/Third-Person-Shooting-Zero#6]
Hello! I'm trying to get this mod to work with the 1.19.2 versions of TacZ and shoulder surfing. It continues to give me an error when it is only those mods enabled.
This is what I get in my logs.

"Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

Full log:
[crash-2024-07-01_16.17.30-client.txt](https://github.com/user-attachments/files/16059782/crash-2024-07-01_16.17.30-client.txt)

**Comment by ChloePrime** [comment]
Fixed in 1.19.2-5.0.2
