### ISSUE TITLE
[Request] TPS:Zero 1.18.2 backport

### ISSUE THREAD

**Issue by ghost** [ChloePrime/Third-Person-Shooting-Zero#8]
Currently, 1.18.2 does not have TAC:Zero compatible versions of Third Person Shooting, and this is something I'd like to see changed.

**Comment by ChloePrime** [comment]
No

**Comment by ChloePrime** [comment]
BTW are you using translation software?
Your request seems threatening, I wonder whether it's caused by flaws of the translation software you're using.

**Comment by ghost** [comment]
No translation software was used. It wasn't my intention to be threatening, apologies.
I was only intending to ask for a 1.18.2 backport. Nothing malicious.
